### PR TITLE
The windows files needed for builds.

### PR DESCRIPTION
**Pull request by derpmarine168**
here you go, after several days. :P

### CODE REVIEW

**Comment by derpmarine168** [comment]
i eventually did it through the web interface. 🙁

**Comment by stefansl** [comment]
Thank you for your work! But why is there some npm command in https://github.com/stefansl/image-shrinker/pull/44/commits/718c856fb46974dcd2c36af100ee2eb0759f96bc

**Comment by derpmarine168** [comment]
yep! sorry about that. i'm just gonna push my fixes. editing on the web ui is trash.

**Comment by derpmarine168** [comment]
oops.

**Comment by derpmarine168** [comment]
i'm just gonna delete this. bad stuff is happening here.

**Comment by derpmarine168** [comment]
af3d94ab-eb67-4e77-bad7-3ade0bcf346a min

fyi, that's what the accidental commit was.

**Comment by derpmarine168** [comment]
i'm making a new pr and i'm gonna use branches this time. 😉

**Comment by derpmarine168** [comment]
<https://github.com/stefansl/image-shrinker/pull/45>. this pr can go and disappear in the hole called closed pull requests.

**Pull request closed without merging**
